/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Font;
import static java.awt.Frame.MAXIMIZED_BOTH;
import java.awt.event.ActionListener;
import javax.swing.BorderFactory;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author EDWIN
 */
public class simulacion extends javax.swing.JFrame {

    /**
     * Creates new form simulacion
     */
    Fondo fondo= new Fondo();
    informacion1 inf= new informacion1();
   private VentanaSimulacionTodo simu;
    private VentanaSimulacionNina simu1;
    private VentanaSimulacionAdolescente simu2;
    private VentanaSimulacionJoven simu3;
    private VentanaSimulacionAdulta simu4;
    
    public simulacion() {
     initComponents();
     this.add(fondo,BorderLayout.CENTER);
     this.pack();
     this.setExtendedState(MAXIMIZED_BOTH);
    // ATRAS.setVisible(false);
       jComboBox1.setVisible(false);
        jComboBox2.setVisible(false);
        jComboBox3.setVisible(false);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        INFORMACION = new javax.swing.JButton();
        SIMULACION = new javax.swing.JButton();
        SALIR = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jComboBox3 = new javax.swing.JComboBox<>();
        SIMULACIONADOLESCENTE = new javax.swing.JButton();
        SIMULACIONJOVEN = new javax.swing.JButton();
        SIMULACIONADULTA = new javax.swing.JButton();
        SIMULACIONNINA = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        INFORMACION.setBackground(new java.awt.Color(0, 153, 204));
        INFORMACION.setText("INFORMACION");
        INFORMACION.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                INFORMACIONActionPerformed(evt);
            }
        });

        SIMULACION.setBackground(new java.awt.Color(0, 153, 204));
        SIMULACION.setText("SIMULACION TODOS");
        SIMULACION.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SIMULACIONActionPerformed(evt);
            }
        });

        SALIR.setBackground(new java.awt.Color(0, 153, 204));
        SALIR.setText(" SALIR");
        SALIR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SALIRActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "3" }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "4" }));
        jComboBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox3ActionPerformed(evt);
            }
        });

        SIMULACIONADOLESCENTE.setBackground(new java.awt.Color(0, 153, 204));
        SIMULACIONADOLESCENTE.setText("SIMULACION  ADOLESCENTE");
        SIMULACIONADOLESCENTE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SIMULACIONADOLESCENTEActionPerformed(evt);
            }
        });

        SIMULACIONJOVEN.setBackground(new java.awt.Color(0, 153, 204));
        SIMULACIONJOVEN.setText("SIMULACION JOVEN");
        SIMULACIONJOVEN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SIMULACIONJOVENActionPerformed(evt);
            }
        });

        SIMULACIONADULTA.setBackground(new java.awt.Color(0, 153, 204));
        SIMULACIONADULTA.setText("SIMULACION ADULTA");
        SIMULACIONADULTA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SIMULACIONADULTAActionPerformed(evt);
            }
        });

        SIMULACIONNINA.setBackground(new java.awt.Color(0, 153, 204));
        SIMULACIONNINA.setText("SIMULACION NIÑAS");
        SIMULACIONNINA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SIMULACIONNINAActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(131, 131, 131)
                        .addComponent(INFORMACION, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(138, 138, 138)
                        .addComponent(SALIR, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(SIMULACION, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(SIMULACIONNINA, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(SIMULACIONADOLESCENTE)
                        .addGap(18, 18, 18)
                        .addComponent(SIMULACIONJOVEN, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(SIMULACIONADULTA)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(287, 287, 287)
                        .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(61, 61, 61))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(SIMULACION, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(SIMULACIONNINA, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(SIMULACIONADOLESCENTE, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(SIMULACIONJOVEN, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(SIMULACIONADULTA, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(30, 30, 30))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(INFORMACION, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SALIR, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SALIRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SALIRActionPerformed
       //this.dispose();
       System.exit(0);
        // TODO add your handling code here:
    }//GEN-LAST:event_SALIRActionPerformed

    private void INFORMACIONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_INFORMACIONActionPerformed
        fondo.setVisible(false);
        INFORMACION.setVisible(false);
    //    ACERCA_DE.setVisible(false);
        SIMULACION.setVisible(false);
        SIMULACIONNINA.setVisible(false);
        SIMULACIONADOLESCENTE.setVisible(false);
        SIMULACIONJOVEN.setVisible(false);
        SIMULACIONADULTA.setVisible(false);
        SALIR.setVisible(false);
        
      //  ATRAS.setVisible(true);
        
        inf.setVisible(true);
        this.add(inf, BorderLayout.CENTER);
        this.pack();
        this.setExtendedState(MAXIMIZED_BOTH);
    }//GEN-LAST:event_INFORMACIONActionPerformed

    private void SIMULACIONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SIMULACIONActionPerformed
        
        int numFiscales = Integer.parseInt(jComboBox1.getSelectedItem().toString());//cb_gastos nº empleados
         int investigaciones =1;
	 int numJueces = Integer.parseInt(jComboBox2.getSelectedItem().toString());
	 int numPersonas = Integer.parseInt(jComboBox3.getSelectedItem().toString());
 	 simu=new VentanaSimulacionTodo(numFiscales,investigaciones,numJueces,numPersonas);	
         simu.setVisible(true);
         this.setVisible(false);

        // TODO add your handling code here:
        //this.setVisible(false);
        //sim.setVisible(true);
       //  int numFiscales = Integer.parseInt(jComboBox2.getSelectedItem().toString());//cb_gastos nº empleados
         //int investigaciones =1;
	 //int numJueces = Integer.parseInt(jComboBox3.getSelectedItem().toString());
	 //int numPersonas = Integer.parseInt(jComboBox1.getSelectedItem().toString());
 	// simu=new VentanaSimulacionTodo(numFiscales,investigaciones,numJueces,numPersonas);			
         //simu.setVisible(true);
         //this.setVisible(false);
        
       
       // sim.simulacionMenu(MENU,getObj());
    }//GEN-LAST:event_SIMULACIONActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jComboBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox3ActionPerformed

    private void SIMULACIONADOLESCENTEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SIMULACIONADOLESCENTEActionPerformed
        // TODO add your handling code here:
                
                int numFiscales = Integer.parseInt(jComboBox1.getSelectedItem().toString());//cb_gastos nº empleados
         int investigaciones =1;
	 int numJueces = Integer.parseInt(jComboBox2.getSelectedItem().toString());
	 int numPersonas = Integer.parseInt(jComboBox3.getSelectedItem().toString());
 	 simu2=new VentanaSimulacionAdolescente(numFiscales,investigaciones,numJueces,numPersonas);	
         simu2.setVisible(true);
         this.setVisible(false);
        
        
        
        
    }//GEN-LAST:event_SIMULACIONADOLESCENTEActionPerformed

    private void SIMULACIONJOVENActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SIMULACIONJOVENActionPerformed
        // TODO add your handling code here:
                
                int numFiscales = Integer.parseInt(jComboBox1.getSelectedItem().toString());//cb_gastos nº empleados
         int investigaciones =1;
	 int numJueces = Integer.parseInt(jComboBox2.getSelectedItem().toString());
	 int numPersonas = Integer.parseInt(jComboBox3.getSelectedItem().toString());
 	 simu3=new VentanaSimulacionJoven(numFiscales,investigaciones,numJueces,numPersonas);	
         simu3.setVisible(true);
         this.setVisible(false);
        
        
    }//GEN-LAST:event_SIMULACIONJOVENActionPerformed

    private void SIMULACIONADULTAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SIMULACIONADULTAActionPerformed
        // TODO add your handling code here:
                
                int numFiscales = Integer.parseInt(jComboBox1.getSelectedItem().toString());//cb_gastos nº empleados
         int investigaciones =1;
	 int numJueces = Integer.parseInt(jComboBox2.getSelectedItem().toString());
	 int numPersonas = Integer.parseInt(jComboBox3.getSelectedItem().toString());
 	 simu4=new VentanaSimulacionAdulta(numFiscales,investigaciones,numJueces,numPersonas);	
         simu4.setVisible(true);
         this.setVisible(false);
        
        
    }//GEN-LAST:event_SIMULACIONADULTAActionPerformed

    private void SIMULACIONNINAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SIMULACIONNINAActionPerformed
        // simulacion de niñas
        
                int numFiscales = Integer.parseInt(jComboBox1.getSelectedItem().toString());//cb_gastos nº empleados
         int investigaciones =1;
	 int numJueces = Integer.parseInt(jComboBox2.getSelectedItem().toString());
	 int numPersonas = Integer.parseInt(jComboBox3.getSelectedItem().toString());
 	 simu1=new VentanaSimulacionNina(numFiscales,investigaciones,numJueces,numPersonas);	
         simu1.setVisible(true);
         this.setVisible(false);
        
        
        
    }//GEN-LAST:event_SIMULACIONNINAActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(simulacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(simulacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(simulacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(simulacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                simulacion s= new simulacion();
                 s.setExtendedState(MAXIMIZED_BOTH);
                 
                s.setVisible(true);
            }
        });
    }
    

  
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton INFORMACION;
    private javax.swing.JButton SALIR;
    private javax.swing.JButton SIMULACION;
    private javax.swing.JButton SIMULACIONADOLESCENTE;
    private javax.swing.JButton SIMULACIONADULTA;
    private javax.swing.JButton SIMULACIONJOVEN;
    private javax.swing.JButton SIMULACIONNINA;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    // End of variables declaration//GEN-END:variables
}
